apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kwok.x-k8s.io/v1alpha1","kind":"Stage","metadata":{"annotations":{},"name":"pod-complete"},"spec":{"next":{"statusTemplate":"{{ $now := Now }}\n{{ $root := . }}\ncontainerStatuses:\n{{ range $index, $item := .spec.containers }}\n{{ $origin := index $root.status.containerStatuses $index }}\n- image: {{ $item.image | Quote }}\n  name: {{ $item.name | Quote }}\n  ready: false\n  restartCount: 0\n  started: false\n  state:\n    terminated:\n      exitCode: 0\n      finishedAt: {{ $now | Quote }}\n      reason: Completed\n      startedAt: {{ $now | Quote }}\n{{ end }}\nphase: Succeeded\n"},"resourceRef":{"apiGroup":"v1","kind":"Pod"},"selector":{"matchExpressions":[{"key":".metadata.deletionTimestamp","operator":"DoesNotExist"},{"key":".status.phase","operator":"In","values":["Running"]},{"key":".metadata.ownerReferences.[].kind","operator":"In","values":["Job"]}]}}}
  creationTimestamp: "2024-12-25T09:34:26Z"
  generation: 1
  name: pod-complete
  resourceVersion: "678723"
  uid: e6824fca-eb4d-48de-884c-a2839bfd395f
spec:
  next:
    statusSubresource: status
    statusTemplate: |
      {{ $now := Now }}
      {{ $root := . }}
      containerStatuses:
      {{ range $index, $item := .spec.containers }}
      {{ $origin := index $root.status.containerStatuses $index }}
      - image: {{ $item.image | Quote }}
        name: {{ $item.name | Quote }}
        ready: false
        restartCount: 0
        started: false
        state:
          terminated:
            exitCode: 0
            finishedAt: {{ $now | Quote }}
            reason: Completed
            startedAt: {{ $now | Quote }}
      {{ end }}
      phase: Succeeded
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: .metadata.deletionTimestamp
      operator: DoesNotExist
    - key: .status.phase
      operator: In
      values:
      - Running
    - key: .metadata.ownerReferences.[].kind
      operator: In
      values:
      - Job
  weight: 0
